//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mMenu
    {
        public int intMenuID { get; set; }
        public Nullable<int> intParentID { get; set; }
        public string txtMenuName { get; set; }
        public string txtDescription { get; set; }
        public Nullable<int> intModuleID { get; set; }
        public string txtLink { get; set; }
        public Nullable<int> intOrderID { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public Nullable<bool> bitMethod { get; set; }
        public string txtIcon { get; set; }
        public string txtGUID { get; set; }
        public string txtCreatedBy { get; set; }
        public Nullable<System.DateTime> dtmCreatedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }
    }
}
