//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mUser()
        {
            this.mUserRoles = new HashSet<mUserRole>();
        }
    
        public int intUserID { get; set; }
        public string txtUserName { get; set; }
        public string txtName { get; set; }
        public int intCompanyID { get; set; }
        public string txtAddress { get; set; }
        public string txtPhoneNumber { get; set; }
        public string txtEmail { get; set; }
        public Nullable<bool> bitActive { get; set; }
        public string txtPassword { get; set; }
        public string txtGUID { get; set; }
        public string txtCreatedBy { get; set; }
        public Nullable<System.DateTime> dtmCreatedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mUserRole> mUserRoles { get; set; }
    }
}
