//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.DAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUserRecord
    {
        public int intUserRecordID { get; set; }
        public int intUserID { get; set; }
        public Nullable<System.DateTime> dtmLastLogin { get; set; }
        public Nullable<int> intWrongPassCount { get; set; }
        public Nullable<System.DateTime> dtmLastWrongPass { get; set; }
        public Nullable<bool> bitLock { get; set; }
        public string txtPreviousPass1 { get; set; }
        public string txtPreviousPass2 { get; set; }
        public string txtPreviousPass3 { get; set; }
    }
}
