//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.Common.Entity
{ 
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        //public DBEntities()
        //    : base("name=DBEntities")
        //{
        //}
        public DBEntities(string connectionString)
            : base(connectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mMenu> mMenus { get; set; }
        public virtual DbSet<mModule> mModules { get; set; }
        public virtual DbSet<mRole> mRoles { get; set; }
        public virtual DbSet<mRoleAccess> mRoleAccesses { get; set; }
        public virtual DbSet<mUser> mUsers { get; set; }
        public virtual DbSet<mUserRole> mUserRoles { get; set; }
        public virtual DbSet<mUserLog> mUserLogs { get; set; }
        public virtual DbSet<mUserRecord> mUserRecords { get; set; }

        public virtual DbSet<mCompany> mCompanies { get; set; }
        public virtual DbSet<mBidangUsaha> mBidangUsahas { get; set; }

        
    }
}
