//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mRoleAccess
    {
        public int intRoleAccessID { get; set; }
        public int intRoleID { get; set; }
        public int intModuleID { get; set; }
        public Nullable<bool> bitEdit { get; set; }
        public Nullable<bool> bitView { get; set; }
        public Nullable<bool> bitDelete { get; set; }
        public Nullable<bool> bitPrint { get; set; }
        public string txtCreatedBy { get; set; }
        public Nullable<System.DateTime> dtmCreatedDate { get; set; }
        public string txtUpdatedBy { get; set; }
        public Nullable<System.DateTime> dtmUpdatedDate { get; set; }

        public virtual mModule mModule { get; set; }
        public virtual mRole mRole { get; set; }
    }
}
