//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemplateWeb.Common.Entity
{
    using System;
    using System.Collections.Generic;

    public partial class mUserLog
    {
        public int intUserLogID { get; set; }
        public int intUserID { get; set; }
        public string txtUrl { get; set; }
        public Nullable<System.DateTime> dtmLog { get; set; }
    }
}
